package VM::HetznerCloud::API::Isos;

# ABSTRACT: Isos

# ---
# This class is auto-generated by bin/get_hetzner_info.pl
# ---

use v5.24;

use Moo;
use Types::Standard qw(:all);

use Mojo::Base -strict, -signatures;

extends 'VM::HetznerCloud::APIBase';

# VERSION

has endpoint  => ( is => 'ro', isa => Str, default => sub { 'isos' } );

sub list ($self, %params) {
    my $request_params = {
        'architecture' => {
            'in'       => 'query',
            'required' => 0,
            'validate' => 'string',
        },
        'include_architecture_wildcard' => {
            'in'       => 'query',
            'required' => 0,
            'validate' => 'boolean',
        },
        'name' => {
            'in'       => 'query',
            'required' => 0,
            'validate' => 'string',
        },
    };
;
    return $self->_request( '', \%params, $request_params, { type => 'get' } );
}

sub get ($self, %params) {
    my $request_params = {
        'id' => {
            'in'       => 'path',
            'required' => 1,
            'validate' => 'int64',
        },
    };
;
    return $self->_request( '/:id', \%params, $request_params, { type => 'get' } );
}


1;

__END__

=pod


=head1 SYNOPSIS

    use VM::HetznerCloud;

    my $api_key = '1234abc';
    my $cloud   = VM::HetznerCloud->new(
        token => $api_key,
    );

    $cloud->records->create(
    );

=head1 ATTRIBUTES

=over 4

=item * endpoint

=back

=head1 METHODS



=head2 list

Returns all available ISO objects.

    $cloud->isos->list(
        architecture => 'test',
        include_architecture_wildcard => 'test',
        name => 'test',
    );


=head2 get

Returns a specific ISO object.

    $cloud->isos->get(
        id => 'test',
    );


    